{% set name = "jupyter-activity-monitor-extension" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_activity_monitor_extension-{{ version }}.tar.gz
  sha256: c31285019a1702eef72735d81268ad3ab2e16d203e66dfc61f265f9f9d91d72b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - jupyter_server >=2.0.0
    - tornado
    - jmespath
    - requests

test:
  imports:
    - jupyter_activity_monitor_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Jupyter Server Extension for checking last activity time
  license: LicenseRef-.amazon.com.-AmznSL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rahrad123
    - agupta01
